-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-07-30 11:21:50 NPT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Ticket CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "User" CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Users CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ShowTime CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Theater_City_Hall CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Movie CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE Movie 
    ( 
     MovieID     NUMBER  NOT NULL , 
     Title       VARCHAR2 (100) , 
     Duration    VARCHAR2 (20) , 
     Language    VARCHAR2 (30) , 
     Genre       VARCHAR2 (30) , 
     ReleaseDate DATE 
    ) 
    LOGGING 
;

ALTER TABLE Movie 
    ADD CONSTRAINT Movie_PK PRIMARY KEY ( MovieID ) ;

CREATE TABLE ShowTime 
    ( 
     ShowTimeID               NUMBER  NOT NULL , 
     MovieID                  NUMBER , 
     HallID                   NUMBER , 
     TicketPrice              NUMBER , 
     Theater_City_Hall_HallID NUMBER  NOT NULL , 
     Movie_MovieID            NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE ShowTime 
    ADD CONSTRAINT ShowTime_PK PRIMARY KEY ( ShowTimeID, Theater_City_Hall_HallID, Movie_MovieID ) ;

CREATE TABLE Theater_City_Hall 
    ( 
     HallID       NUMBER  NOT NULL , 
     TheaterName  VARCHAR2 (100) , 
     TheaterCity  VARCHAR2 (50) , 
     HallCapacity NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE Theater_City_Hall 
    ADD CONSTRAINT Theater_City_Hall_PK PRIMARY KEY ( HallID ) ;

CREATE TABLE Ticket 
    ( 
     TicketID                          NUMBER  NOT NULL , 
     UserID                            NUMBER , 
     MovieID                           NUMBER , 
     HallID                            NUMBER , 
     ShowTimeID                        NUMBER , 
     BookingStatus                     VARCHAR2 (20) , 
     User_UserID                       NUMBER  NOT NULL , 
     ShowTime_ShowTimeID               NUMBER  NOT NULL , 
     ShowTime_HallID                   NUMBER  NOT NULL , 
     ShowTime_Movie_MovieID            NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Ticket
ADD CONSTRAINT Ticket_PK PRIMARY KEY (
    TicketID,
    User_UserID,
    ShowTime_ShowTimeID,
    ShowTime_HallID,
    ShowTime_Movie_MovieID
);

CREATE TABLE Users
    ( 
     UserID   NUMBER  NOT NULL , 
     Username VARCHAR2 (50) , 
     Address  VARCHAR2 (100) 
    ) 
    LOGGING 
;

ALTER TABLE Users 
    ADD CONSTRAINT User_PK PRIMARY KEY ( UserID ) ;

ALTER TABLE ShowTime 
    ADD CONSTRAINT ShowTime_Movie_FK FOREIGN KEY 
    ( 
     Movie_MovieID
    ) 
    REFERENCES Movie 
    ( 
     MovieID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ShowTime 
    ADD CONSTRAINT ShowTime_Theater_City_Hall_FK FOREIGN KEY 
    ( 
     Theater_City_Hall_HallID
    ) 
    REFERENCES Theater_City_Hall 
    ( 
     HallID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Ticket
ADD CONSTRAINT Ticket_ShowTime_FK FOREIGN KEY
(
    ShowTime_ShowTimeID,
    ShowTime_HallID,
    ShowTime_Movie_MovieID
)
    REFERENCES ShowTime 
    ( 
     ShowTimeID,
     Theater_City_Hall_HallID,
     Movie_MovieID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Ticket 
    ADD CONSTRAINT Ticket_User_FK FOREIGN KEY 
    ( 
     User_UserID
    ) 
    REFERENCES Users 
    ( 
     UserID
    ) 
    NOT DEFERRABLE 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USERS                             0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
